# Generated by Django 3.2 on 2023-06-11 07:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingredients',
            new_name='ingredient_id',
        ),
    ]
