# Generated by Django 3.2 on 2023-06-11 08:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0002_rename_ingredients_recipeingredient_ingredient_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingredient_id',
            new_name='ingredient',
        ),
    ]
